[home]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "examples/home_rpc.ipc"
required_confirmations = 0

[home.contract]
bin = "contracts/HomeBridge.bin"

[foreign]
account = "0x004ec07d2329997267Ec62b4166639513386F32E"
ipc = "examples/foreign_rpc.ipc"
required_confirmations = 0

[foreign.contract]
bin = "contracts/ForeignBridge.bin"

[authorities]
accounts = [
	"0x006e27b6a72e1f34c626762f3c4761547aff1421",
]
required_signatures = 1

[transactions]
home_deploy = { gas = 1000000 }
foreign_deploy = { gas = 3000000 }
deposit_relay = { gas = 100000 }
