[parity]
chain = "examples/foreign_spec.json"
base_path = "examples/chains/foreign"

[network]
port = 30301

[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[websockets]
port = 8451

[ipc]
path = "examples/foreign_rpc.ipc"

[account]
unlock = ["0x004ec07d2329997267Ec62b4166639513386F32E"]
password = ["examples/foreign.pwds"]

[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
reseal_on_txs = "none"
usd_per_tx = "0"
reseal_min_period = 0
