[parity]
chain = "examples/home_spec.json"
base_path = "examples/chains/home"

[network]
port = 30300

[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[websockets]
port = 8450

[ipc]
path = "examples/home_rpc.ipc"

[account]
unlock = ["0x006e27b6a72e1f34c626762f3c4761547aff1421"]
password = ["examples/home.pwds"]

[mining]
engine_signer = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
